services:
  - type: web
    name: employee-attendance-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: employee-attendance-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: admin@shop.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: employee-attendance-db
    databaseName: attendanceDB
    user: attendanceuser
